# Generated by Django 4.0.5 on 2022-06-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
